var allPokemonModule = (function () {
  const healthGenerator = (baseHp) => {
    return (level) => {
      return 10 + level + Math.floor(level * 0.01 * 2 * baseHp);
    };
  };

  const ALL_POKEMON = {
    squirtle: {
      id: "0007-squirtle",
      name: "Squirtle",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    bulbasaur: {
      id: "0001-bulbasaur",
      name: "Bulbasaur",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    charmander: {
      id: "0004-charmander",
      name: "Charmander",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    rattata: {
      id: "0019-rattata",
      name: "Rattata",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    raticate: {
      id: "0020-raticate",
      name: "Raticate",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    magnemite: {
      id: "0081-magnemite",
      name: "Magnemite",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    pidgey: {
      id: "0016-pidgey",
      name: "Pidgey",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    pidgeotto: {
      id: "0017-pidgeotto",
      name: "Pidgeotto",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    pidgeott: {
      id: "0018-pidgeott",
      name: "Pidgeotto",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    snorlax: {
      id: "0143-snorlax",
      name: "Snorlax",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    butterfree: {
      id: "0012-butterfree",
      name: "Butterfree",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    beedrill: {
      id: "0015-beedrill",
      name: "Beedrill",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    kakuna: {
      id: "0014-kakuna",
      name: "Kakuna",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    weedle: {
      id: "0013-weedle",
      name: "Weedle",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    caterpie: {
      id: "0010-caterpie",
      name: "Caterpie",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
    metapod: {
      id: "0011-metapod",
      name: "Metapod",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
    },
  };
  

  return {
    ALL_POKEMON
  }
})();

