var pokemonModule = (function () {
  const healthGenerator = (baseHp) => {
    return (level) => {
      return 10 + level + Math.floor(level * 0.01 * 2 * baseHp);
    };
  };

  const ALL_POKEMON = {
    squirtle: {
      id: "0007-squirtle",
      name: "Squirtle",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 15000,
    },
    bulbasaur: {
      id: "0001-bulbasaur",
      name: "Bulbasaur",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 15000,
    },
    charmander: {
      id: "0004-charmander",
      name: "Charmander",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 15000,
    },
    rattata: {
      id: "0019-rattata",
      name: "Rattata",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 1000,
    },
    raticate: {
      id: "0020-raticate",
      name: "Raticate",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    magnemite: {
      id: "0081-magnemite",
      name: "Magnemite",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    pidgey: {
      id: "0016-pidgey",
      name: "Pidgey",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 1000,
    },
    pidgeotto: {
      id: "0017-pidgeotto",
      name: "Pidgeotto",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    pidgeott: {
      id: "0018-pidgeott",
      name: "Pidgeotto",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 15000,
    },
    spearow: {
      id: "0021-spearow",
      name: "Spearow",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 1000,
    },
    fearow: {
      id: "0022-fearow",
      name: "Fearow",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    ekans: {
      id: "0023-ekans",
      name: "Ekans",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 1000,
    },
    arbok: {
      id: "0024-arbok",
      name: "Arbok",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    pikachu: {
      id: "0025-pikachu",
      name: "Pikachu",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    raichu: {
      id: "0026-raichu",
      name: "Raichu",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 15000,
    },
    mew: {
      id: "0151-mew",
      name: "Mew",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 100000,
    },
    eevee: {
      id: "0133-eevee",
      name: "Eevee",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 15000,
    },
    mimikyu: {
      id: "0778-mimikyu",
      name: "Mimikyu",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    jigglypuff: {
      id: "0039-jigglypuff",
      name: "Jigglypuff",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 2000,
    },
    rockruff: {
      id: "0744-rockruff",
      name: "Rockruff",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    snorlax: {
      id: "0143-snorlax",
      name: "Snorlax",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 25000,
    },
    butterfree: {
      id: "0012-butterfree",
      name: "Butterfree",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    beedrill: {
      id: "0015-beedrill",
      name: "Beedrill",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 5000,
    },
    kakuna: {
      id: "0014-kakuna",
      name: "Kakuna",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 2000,
    },
    weedle: {
      id: "0013-weedle",
      name: "Weedle",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 500,
    },
    caterpie: {
      id: "0010-caterpie",
      name: "Caterpie",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 500,
    },
    metapod: {
      id: "0011-metapod",
      name: "Metapod",
      health: healthGenerator(30),
      moves: ["tackle"],
      specialDefenceGrowth: 2,
      physicalDefenceGrowth: 3,
      specialDamageGrowth: 3,
      physicalDamageGrowth: 1,
      baseExp: 100,
      basePrice: 2000,
    },
  };
  

  return {
    ALL_POKEMON
  }
})();

